In [2]:
import pandas as pd

In [52]:

data = pd.read_csv("out/menu.csv", index_col="Unnamed: 0")
data.head()

,select,category,category_de,category_nl,name,name_de,algorithmus,description,statistical_basis,name_nl,source_de,source_id_de,source_nl,source_id_nl,Zeitbezug_min,Zeitbezug_max,Gemeinden,Gemeindeverbände,Kreise
0,NaN,NaN,Absolutzahlen,NaN,NaN,Arbeitslose,NaN,NaN,NaN,NaN,Inkar,2176,NaN,NaN,1995,2020,NaN,X,X
1,NaN,NaN,Absolutzahlen,NaN,NaN,Bevölkerung (mit Korrektur VZ 1987/Zensus 2011),NaN,NaN,NaN,NaN,Inkar,10806,NaN,NaN,1995,2020,NaN,X,X
2,NaN,NaN,Absolutzahlen,NaN,NaN,Bevölkerung gesamt,NaN,NaN,NaN,NaN,Inkar,12586,NaN,NaN,1995,2020,NaN,X,X
3,NaN,NaN,Absolutzahlen,NaN,NaN,Bevölkerung männlich,NaN,NaN,NaN,NaN,Inkar,12747,NaN,NaN,1995,2020,NaN,X,X
4,NaN,NaN,Absolutzahlen,NaN,NaN,Bevölkerung weiblich,NaN,NaN,NaN,NaN,Inkar,12746,NaN,NaN,1995,2020,NaN,X,X

In [64]:
inkar_übersicht_raum = pd.read_excel("model_translator\Übersicht der Indikatoren.xlsx", sheet_name=0)
inkar_übersicht_ZOM = pd.read_excel("model_translator\Übersicht der Indikatoren.xlsx", sheet_name=1)
inkar_übersicht_SDG = pd.read_excel("model_translator\Übersicht der Indikatoren.xlsx", sheet_name=2)


inkar_übersicht_raum = inkar_übersicht_raum.replace(';', '!.', regex=True)
inkar_übersicht_raum = inkar_übersicht_raum.replace('\n', '', regex=True)

inkar_übersicht_ZOM = inkar_übersicht_ZOM.replace(';', '!.', regex=True)
inkar_übersicht_ZOM = inkar_übersicht_ZOM.replace('\n', '', regex=True)

inkar_übersicht_SDG = inkar_übersicht_SDG.replace(';', '!.', regex=True)
inkar_übersicht_SDG = inkar_übersicht_SDG.replace('\n', '', regex=True)

inkar_übersicht_raum.to_csv("inkar_übersicht_raum.csv", index=False)
inkar_übersicht_raum = pd.read_csv("inkar_übersicht_raum.csv")

inkar_übersicht_ZOM.to_csv("inkar_übersicht_ZOM.csv", index=False)
inkar_übersicht_ZOM = pd.read_csv("inkar_übersicht_ZOM.csv")

inkar_übersicht_SDG.to_csv("inkar_übersicht_SDG.csv", index=False)
inkar_übersicht_SDG = pd.read_csv("inkar_übersicht_SDG.csv")

c:\Users\juliu\VSCODE\VSCODE\inkar-indicators\.venv\lib\site-packages\openpyxl\reader\workbook.py:118: UserWarning: Print area cannot be set to Defined name: 'Raumbeobachtung DE'!$C:$K.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")
c:\Users\juliu\VSCODE\VSCODE\inkar-indicators\.venv\lib\site-packages\openpyxl\reader\workbook.py:118: UserWarning: Print area cannot be set to Defined name: 'Raumbeobachtung DE'!$C:$K.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")
c:\Users\juliu\VSCODE\VSCODE\inkar-indicators\.venv\lib\site-packages\openpyxl\reader\workbook.py:118: UserWarning: Print area cannot be set to Defined name: 'Raumbeobachtung DE'!$C:$K.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")

In [67]:

d = inkar_übersicht_ZOM.columns.tolist()
print(d)

['Unnamed: 0', 'Unnamed: 1', 'INKAR 2022 – Indikatorenübersicht:   Zentrale-Orte-Monitoring (ZOM)', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']

In [72]:
colums = ['INKAR 2022 – Indikatorenübersicht:   Raumbeobachtung Deutschland', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6']
inkar_übersicht_raum = inkar_übersicht_raum.loc[:, colums]


colums = ['INKAR 2022 – Indikatorenübersicht:   Sustainable Development Goals (SDG)', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6']
inkar_übersicht_SDG = inkar_übersicht_SDG.loc[:, colums]

colums = ['INKAR 2022 – Indikatorenübersicht:   Zentrale-Orte-Monitoring (ZOM)', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6']
inkar_übersicht_ZOM = inkar_übersicht_ZOM.loc[:, colums]

inkar_übersicht_raum.head()
#inkar_übersicht_SDG.head()
#inkar_übersicht_ZOM.head()

,INKAR 2022 – Indikatorenübersicht: Raumbeobachtung Deutschland,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,NaN
1,Kurzname,Algorithmus,Anmerkungen,Statistische Grundlagen
2,Absolutzahlen,NaN,NaN,NaN
3,Bodenfläche gesamt qkm,NaN,Als Katasterfläche bezeichnet man den vermessu...,Flächenerhebung nach Art der tatsächlichen Nut...
4,Bevölkerung gesamt,NaN,Es handelt sich um die Zahl der Einwohner zum ...,Fortschreibung des Bevölkerungsstandes des Bun...

In [73]:
for index in inkar_übersicht_raum.index:
    if (index == 0 or index == 1 or index == 2):
        continue
    algorithmus = inkar_übersicht_raum['Unnamed: 4'][index]
    description = inkar_übersicht_raum['Unnamed: 5'][index]
    statistical_basis = inkar_übersicht_raum['Unnamed: 6'][index]
    name_description = inkar_übersicht_raum['INKAR 2022 – Indikatorenübersicht:   Raumbeobachtung Deutschland'][index]
    for i in data.index:
        name_de = data['name_de'][i]
        if(name_description == name_de):
            data['description'][i] = description
            data['statistical_basis'][i] = statistical_basis
            data['algorithmus'][i] = algorithmus

for index in inkar_übersicht_SDG.index:
    if (index == 0 or index == 1 or index == 2):
        continue
    algorithmus = inkar_übersicht_SDG['Unnamed: 4'][index]
    description = inkar_übersicht_SDG['Unnamed: 5'][index]
    statistical_basis = inkar_übersicht_SDG['Unnamed: 6'][index]
    name_description = inkar_übersicht_SDG['INKAR 2022 – Indikatorenübersicht:   Sustainable Development Goals (SDG)'][index]
    for i in data.index:
        name_de = data['name_de'][i]
        if(name_description == name_de):
            data['description'][i] = description
            data['statistical_basis'][i] = statistical_basis
            data['algorithmus'][i] = algorithmus

for index in inkar_übersicht_ZOM.index:
    if (index == 0 or index == 1 or index == 2):
        continue
    algorithmus = inkar_übersicht_ZOM['Unnamed: 4'][index]
    description = inkar_übersicht_ZOM['Unnamed: 5'][index]
    statistical_basis = inkar_übersicht_ZOM['Unnamed: 6'][index]
    name_description = inkar_übersicht_ZOM['INKAR 2022 – Indikatorenübersicht:   Zentrale-Orte-Monitoring (ZOM)'][index]
    for i in data.index:
        name_de = data['name_de'][i]
        if(name_description == name_de):
            data['description'][i] = description
            data['statistical_basis'][i] = statistical_basis
            data['algorithmus'][i] = algorithmus

data.head()

,select,category,category_de,category_nl,name,name_de,algorithmus,description,statistical_basis,name_nl,source_de,source_id_de,source_nl,source_id_nl,Zeitbezug_min,Zeitbezug_max,Gemeinden,Gemeindeverbände,Kreise
0,NaN,NaN,Absolutzahlen,NaN,NaN,Arbeitslose,NaN,Es handelt sich um die Zahl der Arbeitslosen i...,Arbeitsmarktstatistik der Bundesagentur für Ar...,NaN,Inkar,2176,NaN,NaN,1995,2020,NaN,X,X
1,NaN,NaN,Absolutzahlen,NaN,NaN,Bevölkerung (mit Korrektur VZ 1987/Zensus 2011),NaN,Zwischen der Zahl der Bevölkerung am 31.12.201...,"Bundesinstitut für Bau-, Stadt- und Raumforsch...",NaN,Inkar,10806,NaN,NaN,1995,2020,NaN,X,X
2,NaN,NaN,Absolutzahlen,NaN,NaN,Bevölkerung gesamt,NaN,Es handelt sich um die Zahl der Einwohner zum ...,Fortschreibung des Bevölkerungsstandes des Bun...,NaN,Inkar,12586,NaN,NaN,1995,2020,NaN,X,X
3,NaN,NaN,Absolutzahlen,NaN,NaN,Bevölkerung männlich,NaN,Es handelt sich um die Zahl der männlichen Ein...,Fortschreibung des Bevölkerungsstandes des Bun...,NaN,Inkar,12747,NaN,NaN,1995,2020,NaN,X,X
4,NaN,NaN,Absolutzahlen,NaN,NaN,Bevölkerung weiblich,NaN,Es handelt sich um die Zahl der weiblichen Ein...,Fortschreibung des Bevölkerungsstandes des Bun...,NaN,Inkar,12746,NaN,NaN,1995,2020,NaN,X,X

In [75]:
data.to_csv("data_with_description.csv", index=False)