In [ ]:

import pandas as pd
import numpy as np

In [ ]:

data = pd.read_csv("out/translated_data.csv", index_col="Unnamed: 0")
data.head()

In [ ]:
indicators = pd.DataFrame(columns=['category', 'name', 'source', 'source_id'])  # Erstellen Sie ein leeres DataFrame mit der gewünschten Spalte

for index in data.index:
    if data['select'][index] == "x":
        print(index)
        category_value = data['category_de'][index]
        indicator_name = data['name_de'][index]
        source_value = data['source_de'][index]
        source_id_value = int(data['source_id_de'][index])
        indicators.loc[len(indicators)] = {'category': category_value, 'name': indicator_name, 'source': source_value, 'source_id':source_id_value}


# Optional: Wenn Sie den Index neu sortieren möchten
indicators.reset_index(drop=True, inplace=True)
indicators

In [ ]:
inkar = pd.read_csv("../data/inkar_2022.csv",sep=";",decimal=",",dtype={'Kennziffer':str,'Kennziffer_EU':str,'Name':str}, low_memory=False)
inkar.head()

In [95]:
filtered_inkar = inkar[(inkar['Bereich'].isin(indicators['category'])) & (inkar['ID'].isin(indicators['source_id'])) & (inkar['Indikator'].isin(indicators['name']))]
filtered_inkar.reset_index(drop=True, inplace=True)
filtered_inkar

#filtered_inkar.to_csv("C:/Users/juliu/VSCODE/VSCODE/inkar-indicators/src/out/test2.csv")

,Bereich,ID,Indikator,Raumbezug,Kennziffer,Name,Zeitbezug,Wert
0,Absolutzahlen,10806,Bevölkerung (mit Korrektur VZ 1987/Zensus 2011),Arbeitsmarktregionen,001,Flensburg,1995,273171.00
1,Absolutzahlen,10806,Bevölkerung (mit Korrektur VZ 1987/Zensus 2011),Arbeitsmarktregionen,001,Flensburg,1996,274682.00
2,Absolutzahlen,10806,Bevölkerung (mit Korrektur VZ 1987/Zensus 2011),Arbeitsmarktregionen,001,Flensburg,1997,275463.00
3,Absolutzahlen,10806,Bevölkerung (mit Korrektur VZ 1987/Zensus 2011),Arbeitsmarktregionen,001,Flensburg,1998,275958.00
4,Absolutzahlen,10806,Bevölkerung (mit Korrektur VZ 1987/Zensus 2011),Arbeitsmarktregionen,001,Flensburg,1999,277141.00
...,...,...,...,...,...,...,...,...
372521,Privateinkommen und private Schulden,17479,Bruttoverdienst im Produzierenden Gewerbe,West-Ost,2,Ost,2016,2784.09
372522,Privateinkommen und private Schulden,17479,Bruttoverdienst im Produzierenden Gewerbe,West-Ost,2,Ost,2017,2851.98
372523,Privateinkommen und private Schulden,17479,Bruttoverdienst im Produzierenden Gewerbe,West-Ost,2,Ost,2018,2941.87
372524,Privateinkommen und private Schulden,17479,Bruttoverdienst im Produzierenden Gewerbe,West-Ost,2,Ost,2019,3023.38
372525,Privateinkommen und private Schulden,17479,Bruttoverdienst im Produzierenden Gewerbe,West-Ost,2,Ost,2020,3005.60